[platformio]
default_envs = esp32-c3-devkitm-1

[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_protocol = esptool
board_build.partitions = huge_app.csv
build_unflags = 
    -std=gnu++11
build_flags = 
    -std=gnu++17
    -Wall
lib_deps =
    lovyan03/LovyanGFX
    tzapu/WiFiManager
    mathieucarbou/ESP Async WebServer
    mathieucarbou/AsyncTCP
    bblanchon/ArduinoJson

[env:esp32-c3-devkitm-1]
monitor_port = /dev/cu.usbmodem1101
upload_port = /dev/cu.usbmodem1101
build_flags = 
    ${env.build_flags}
    -D ESP32C3_GENERIC=1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:esp32c3-crowpanel]
upload_speed = 1500000
build_flags = 
    ${env.build_flags}
    -D ESP32C3_ELECROW=1

